### ISSUE TITLE
Getting illegal URI exception while taking msg-vpn backup

### ISSUE THREAD

**Issue by sandip22c** [flyisland/solconfig#1]
Hello Team,

I'm receiving illegal UI exception while taking backup of msg-vpn which contains bridge.
Please find error below:
java.net.URISyntaxException: Illegal character in scheme name at index 0: 127.0.0.1:55443

127.0.0.1:55443 is the part of remoteMsgVpn in bridge.

**Comment by flyisland** [comment]
@sandip22c could you please provide more detailed info like:
1. java version, os version
2. the whole command line and output

**Comment by sandip22c** [comment]
Hello @flyisland 

Please find the details below
OS Version: CentOS Linux release 7.9.2009 (Core)
Java:
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05)
OpenJDK 64-Bit Server VM GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05, mixed mode, sharing)
Command Line: solconfig -k -H https://127.0.0.1:443 -u ********* -p ******** backup vpn test_vpn

Due to some security concerns I cannot share stack trace in  plain text, hence sharing as a pdf link.
First Half: https://github.com/sandip22c/raw_data/blob/master/solace_1.pdf
Second Half: https://github.com/sandip22c/raw_data/blob/master/solace_2.pdf

The above said command line works perfectly if msg-vpn does not have any bridge configured.
It fails to backup when msg-vpn has bridge remoteMsgVpn configuration, which has "ip:port" as a value.

Thanks in advance :)

**Comment by flyisland** [comment]
@sandip22c I still need the whole output to try to understand what happens, and the graalvm native image is not as mature as I expected, I'd recommend you to try the jar version.

Or you could try the latest release v1.1.2 to check if it could solve this issue.

Please let me know the result, thanks.

**Comment by sandip22c** [comment]
@flyisland I shared the complete output at pdf files.
And already tried solconfig latest release(v1.1.2), but no success.
Will check with Jar file & update you.

Thanks

**Comment by sandip22c** [comment]
@flyisland I tested with jar version, no success. Getting same error.

Thanks

**Comment by flyisland** [comment]
I've just tried to back up a vpn with a bridge configured, no errors.

```json
      "bridges": [
        {
          "bridgeName": "test_vpn_eb01",
          "bridgeVirtualRouter": "auto",
          "enabled": true,
          "remoteAuthenticationBasicClientUsername": "bridge",
          "remoteAuthenticationBasicPassword": "",
          "remoteMsgVpns": [
            {
              "enabled": true,
              "queueBinding": "test_vpn_eb01_Queue",
              "remoteMsgVpnInterface": "",
              "remoteMsgVpnLocation": "mr-8hal32qwp0v.messaging.solace.cloud:55443",
              "remoteMsgVpnName": "eb01",
              "tlsEnabled": true
            }
          ],
          "remoteSubscriptions": [
            {
              "deliverAlwaysEnabled": false,
              "remoteSubscriptionTopic": "bridge/test"
            }
          ]
        }
      ],

```

**Comment by flyisland** [comment]
@sandip22c 

I was able to reproduce this issue with "ip:port" as the value of "remoteMsgVpnLocation", please wait for my next update.

**Comment by flyisland** [comment]
@sandip22c, please 'git pull' the latest update, it should be able to solve this issue.

**Comment by sandip22c** [comment]
Hello @flyisland 

Tested the issue with the latest updates, its working properly.
Thanks for quick turnaround.

This utility is really helpful. Much appreciated all your efforts.

We can close this issue. Thanks again.
