### ISSUE TITLE
Does not fetch replication mode data along with replicated topics

### ISSUE THREAD

**Issue by sandip22c** [flyisland/solconfig#2]
Hello @flyisland 

Utility fetching the list of configured replicated topics under msg-vpn, but without replication mode which are configured for each topic.
If possible can you check and consider this enhancement.

**Comment by flyisland** [comment]
@sandip22c could you share more details for me to understand the requirement, for example, the screenshot of your configuration web page and the JSON snippet of the backup.

**Comment by sandip22c** [comment]
Hello @flyisland 

Please find below screenshot below.
[Replication Mode](https://github.com/sandip22c/raw_data/raw/master/solace_backup/solace_rep_mode.JPG)

At present the backup JSON snippet is like below(without replication Mode):
`
"replicatedTopics": [
  {
    "replicatedTopic": "UK/TEST/001"
  },
  {
    "replicatedTopic": "UK/TEST/002"
  },
  {
    "replicatedTopic": "UK/TEST/003"
  }
]
`


But it should be like below, because whenever we configure replicated topic its with replication mode only.
`
"replicatedTopics": [
  {
    "replicatedTopic": "UK/TEST/001",
    **"replicationMode": "async"**
  },
  {
    "replicatedTopic": "UK/TEST/002",
    **"replicationMode": "async"**
  },
  {
    "replicatedTopic": "UK/TEST/003",
    **"replicationMode": "async"**
  }
]
`

Thanks

**Comment by flyisland** [comment]
Hi @sandip22c 

The default value of replicationMode is "async", this is an intended design to ignore the attributes with a default value to keep the JSON output more concise since the PS+ SEMPv2 will set the missing attributes with a default value while creating or updating an object.

Anyway, I think I could add a "keep attributes with a default value" option for the `backup` command on a future release.

Please let me know if you could `create` or `update` a VPN successfully with this JSON file, thanks.

**Comment by sandip22c** [comment]
Hello @flyisland 

This is true that "async" is the default value, but in our env there are some msg-vpn  replicated topics configured with replication mode as "sync".
That's the reason we are expecting this attribute to be added in backup JSON.

Thanks

**Comment by flyisland** [comment]
@sandip22c do you mean even with replicationMode set to "sync", you still can not find it in the backup output?

> This is true that "async" is the default value, but in our env there are some msg-vpn replicated topics configured with replication mode as "sync".

**Comment by flyisland** [comment]
> add "--keep-default" option to `backup` command to indicate whether to Keep attributes with a default value

@sandip22c, please pull the repo to check if this new option meets your requirement.

**Comment by sandip22c** [comment]
Hello @flyisland 
Sure will check

**Comment by sandip22c** [comment]
Hello @flyisland 
Checked with latest, working properly.

Thanks for your support.
