### ISSUE TITLE
Getting IllegalArgumentException for SEMPv2 version

### ISSUE THREAD

**Issue by sandip22c** [flyisland/solconfig#3]
Hello @flyisland 

I'm facing issues while taking backup. Getting IllegalArgumentException for SEMPv2 version.
Please find below screenshot for your ref.
https://raw.githubusercontent.com/sandip22c/raw_data/master/solace_backup/semp_backup.JPG

**Comment by flyisland** [comment]
@sandip22c could you show me the result of `curl http://brokerIP:8080/SEMP/v2/config/about/api`, it should return a json like below

```json
{
    "data":{
        "platform":"VMR",
        "sempVersion":"2.22"
    },
    "links":{
        "uri":"http://localhost:8080/SEMP/v2/config/about/api"
    },
    "meta":{
        "request":{
            "method":"GET",
            "uri":"http://localhost:8080/SEMP/v2/config/about/api"
        },
        "responseCode":200
    }
}
```

**Comment by sandip22c** [comment]
Hello @flyisland 
Please find below attached details.
https://raw.githubusercontent.com/sandip22c/raw_data/master/solace_backup/semp_about.JPG

**Comment by flyisland** [comment]
Interesting, this is the first time I saw the sempVersin in such format, could you tell me the version of the broker, you could find it at the left-down corner of the web console.

**Comment by sandip22c** [comment]
Its "Appliance 9.1.1.36"

**Comment by flyisland** [comment]
please check https://github.com/flyisland/solconfig/releases/tag/v1.1.3, it should resolve this issue

**Comment by sandip22c** [comment]
> please check https://github.com/flyisland/solconfig/releases/tag/v1.1.3, it should resolve this issue

Hello @flyisland 
Tried with this, no success. Getting same error.

**Comment by flyisland** [comment]
Did you try the jar directly, or compile it from the source? Please make sure you use the jar file directly.

**Comment by sandip22c** [comment]
Hello @flyisland 
Yes, I was trying with compiled binary.
Now tried with jar given in link, its working.

Actually the problem with using jar is that it has Java 11 dependency.
That's the reason I'm using compiled binary which does not have any external dependency.

**Comment by sandip22c** [comment]
Does the jar compatible with OpenJDK 11?

**Comment by flyisland** [comment]
> Does the jar compatible with OpenJDK 11?

Yes, and I just pushed in the latest source code, you can just clone it and build your own binary.
