### ISSUE TITLE
Unable to fetch subscriptions for Durable Topic Endpoints

### ISSUE THREAD

**Issue by sandip22c** [flyisland/solconfig#4]
Hello @flyisland 
I'm unable to fetch topic subscription configured for Durable Topic Endpoints(DTE) like.
I can see it configured for DTE in vpn as "destinationTopics", but its not getting reflected in backup.

**Comment by flyisland** [comment]
This is expected behavior, the topic subscription of a DTE is not a configuration item.  Please check https://docs.solace.com/Configuring-and-Managing/Configuring-DTEs.htm

> The topic subscription that a topic endpoint will spool messages for is not specified when a topic endpoint is provisioned; it is specified by a client when that client requests to bind a consumer flow to the topic endpoint
