### ISSUE TITLE
HTTPS endpoint getting converted to HTTP

### ISSUE THREAD

**Issue by franklin-antony** [flyisland/solconfig#6]
Hello @flyisland ,
  I noticed a problem while trying to take a backup.
  The endpoint [ https://dev-event*************  ] is SSL enabled on the Load Balancer. So SSL Termination happens on the LB.

D:\Softwares\Solace-Config>java -jar solconfig.jar -H **https://dev-event*************** -u XXXXXX -p "XXXXXXX"  backup vpn default > solace_dev.json
GET **http://dev-event***************/SEMP/v2/config/msgVpns/default/aclProfiles with playload:
null
java.io.IOException: HTTP/1.1 header parser received no bytes
java.io.IOException: HTTP/1.1 header parser received no bytes
        at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:565)
        at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:119)
        at com.solace.tools.solconfig.SempClient.sendWithAbsoluteURI(SempClient.java:193)
        at com.solace.tools.solconfig.SempClient.getCollectionWithAbsoluteUri(SempClient.java:151)

For some reason the request gets converted to HTTP instead of HTTPS

The SOLACE broker communicates on the clear text(NO SSL)

**Comment by flyisland** [comment]
Hi Franklin, not sure why this would happen. 

Could you please run `curl -i -u <adminuser>:<adminpwd> https://dev-event*************)/SEMP/v2/config/msgVpns/default` and paste the output here

**Comment by franklin-antony** [comment]
Yup. I think that is the issue. I just kept the important parts for now.

    },
    "links": {
       "authenticationOauthProvidersUri": "http://dev-even******************/SEMP/v2/config/msgVpns/default/authenticationOauthProviders",
        "authorizationGroupsUri": "http://dev-even******************/SEMP/v2/config/msgVpns/default/authorizationGroups",
        "bridgesUri": "http://dev-even******************/SEMP/v2/config/msgVpns/default/bridges",
        "clientProfilesUri": "http://dev-even******************/SEMP/v2/config/msgVpns/default/clientProfiles",
        "clientUsernamesUri": "http://dev-even******************/SEMP/v2/config/msgVpns/default/clientUsernames",
        "distributedCachesUri": "http://dev-even******************/SEMP/v2/config/msgVpns/default/distributedCaches",

}

**Comment by flyisland** [comment]
Yes, since the LB terminates the SSL, the broker was actually called by HTTP only, that's why it returned links starting with HTTP only.

Could you run the `solconfig` behind the LB?

**Comment by franklin-antony** [comment]
I will try to ask the LB team to see if we can force requests towards HTTP ->redirected to -> HTTPS.
I dont think there is much we could do in the `solconfig`

**Comment by flyisland** [comment]
btw, if you want to back up the sensitive attributes like passwords, you must provide the `solconfig`  the host URL starting with "HTTPS" and an opaque password. Please check the "Opaque Password" section in the [README](https://github.com/flyisland/solconfig#readme) for more details.
