### ISSUE TITLE
Null pointer exception while taking backup

### ISSUE THREAD

**Issue by Kvdatta** [flyisland/solconfig#8]
Hi @flyisland ,

While taking vpn backup for few vpns we are getting nullpointer exception error. Please find attached image.

![IMG_20221031_173122](https://user-images.githubusercontent.com/117084934/199003345-4cd4e5d5-4d84-4738-bc84-b65a2f874a10.jpg)

**Comment by flyisland** [comment]
Hi Kvdatta, could you provide more information:
1. the version of Solace PS+
2. the version of solconfig, 
3. the parameters you used and the entire output of solconfig

**Comment by Kvdatta** [comment]
Hi @flyisland ,

We are using sempv2
Solconfig: 1.1.3
java -jar solconfig.jar -k -H https://solace.******* -u user -p passwd backup vpn vpnname

Kindly find the attachment.

FYI, we are facing this issue only in two vpns, remaining vpns are working fine with this setup.

![IMG20221102213052](https://user-images.githubusercontent.com/117084934/199544834-ec09827e-93c7-4571-bed6-08f4ec145e16.jpg)j
![IMG20221102211254](https://user-images.githubusercontent.com/117084934/199544849-e4d5e85d-0fa6-4af0-877e-2f94b2b9affa.jpg)

![IMG20221102213214](https://user-images.githubusercontent.com/117084934/199544819-afaf0851-9ea7-4e2c-8b30-917fa2cb8285.jpg)

**Comment by flyisland** [comment]
Hi @Kvdatta ,
The version of solconfig is 1.1.3, which is outdated. Please use the latest version and try it again.

**Comment by Kvdatta** [comment]
hi @flyisland ,

I see you have fixed this issue in v1.1.5,make sense, I will update the solconfig and try again. will update you once done
Thanks for quick response

[fix]Got NullPointerException while applying create or backup commands with only a file name with no folder prefix.

**Comment by Kvdatta** [comment]
Hi @flyisland ,

Tested with latest version solconfig file. It worked
Thanks
