### ISSUE TITLE
Unable to backup more than 1000+ DTE or Queue

### ISSUE THREAD

**Issue by sandip22c** [flyisland/solconfig#9]
Hello,

Unable to backup the DTE or Queue objects if it's more than 1000.
Backup happening only till 1000.

Java Version: JDK 11
Solconfig Version: 1.1.7

Kindly suggest.

**Comment by flyisland** [comment]
@sandip22c, is there any error?

What's the version of the broker?

**Comment by sandip22c** [comment]
@flyisland, please find version below.
SolOS Version 9.3

No error, but it fetches only 1000 object, not more than that.

**Comment by flyisland** [comment]
@sandip22c do you mean you have more than 1000 queues configured on the VPN, but the output of `solconfig backup vpn` shows only 1000 queues?

**Comment by sandip22c** [comment]
Correct, there are some VPN's with more than 1000 queue and DTE.
We are facing this issue for those VPN's only.

**Comment by flyisland** [comment]
@sandip22c, I don't have a v9.3 env, I just tried to backup a VPN with 1005 queues on the latest version v10.2.1.32, everything is fine.

I created a new branch to add some debug info, please follow below commands and share with me the backup json file, thanks.

```
git clone https://github.com/flyisland/solconfig.git
cd solconfig
git checkout add_debug
./gradlew jar
java -jar build/libs/solconfig.jar backup vpn yourVPN > /tmp/yourVPN.json
```

**Comment by sandip22c** [comment]
@flyisland 
Let me check this, will update you the status.

**Comment by sandip22c** [comment]
Hello @flyisland,
Sorry for the delay.
Utility seems working properly.
Issues is with our two particular broker.
We are in discussion with support & they suggested to upgrade the same.
Thanks for you kind support.
Closing the issue.
